config/routes.rb
Rails.application.routes.draw do

  get 'book_comments/create'
  get 'book_comments/destroy'
  devise_for :users


  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
      # フォロー一覧
      get :follows, on: :member
      # フォロワー一覧
      get :followers, on: :member
  end

  resources :books do
  	resource :favorites, only: [:create, :destroy]
    resources :book_comments,only: [:create,:destroy]
  end

  root 'home#top'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates_uniqueness_of :book_id,scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	# UserモデルをFollowing,Followerモデルと呼ぶ
	belongs_to :following, class_name:"User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable,:validatable

  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  attachment :profile_image, destroy: false

  # コメント機能
  has_many :book_comments, dependent: :destroy

  # いいね機能
  has_many :favorites, dependent: :destroy


  # フォロー取得
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「following」と定義
  has_many :followings, through: :active_relationships, source: :follower

  # フォロワーの取得
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followed」と定義
  has_many :followers, through: :passive_relationships, source: :following

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。

  # いいね機能
  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
    # selfにはcurrent_userが入る
  end

  # フォロー済みか判定
  def followed_by?(user)
      passive_relationships.find_by(following_id: user.id).present?
  end

  # フォローを外す機能
  # def unfollow(user_id)
  #   active_relationships.find_by(follower_id: user.id).destroy
  # end

  # フォロー機能
  # def follow(user_id)
  #   active_relationships.create(follower_id: user_id)
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
  	book = Book.find(params[:book_id])
  	comment = current_user.book_comments.new(book_comment_params)
  	comment.book_id = book.id
  	comment.save
  	redirect_to book_path(book)
  end

  def destroy
  	BookComment.find_by(id: params[:id],book_id: params[:book_id]).destroy
  	redirect_to book_path(params[:book_id])
  end

  private
  def book_comment_params
  	params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,only: [:index,:show,:edit]

  def show
  	@book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id #追記


    if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title,:body,:user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		# book = Book.find(params[:book_id])
		@favorite = current_user.favorites.create(book_id: params[:book_id])
		# favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@book = Book.find(params[:book_id])
		@favorite = current_user.favorites.find_by(book_id: @book.id)
		@favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    if follow.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    if follow.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update]
  before_action :authenticate_user!,only: [:index,:show,:edit]
  # ログインしていない場合使えない

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
    if current_user !=@user
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
    @book = Book.new
    @books = Book.all
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
    # render 'show_follow'
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
    # render 'show_follower'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止 メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/_newform.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <ul>
    	<h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :opinion %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "Create Book",class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<% if @book.errors.any? %>
		<div id="error_explanation">
			<ul>
				<h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>


		<h1>Editing Book</h1>

		<%= form_for(@book) do |f| %>
		<div class="field row">
			<%= f.label :title %>
			<%= f.text_field :title, class: "col-xs-12 @book_title" %>
		</div>

		<div class="field row">
			<%= f.label :opinion %> <!-- ここを変更 -->
			<%= f.text_area :body, class: "col-xs-12 @book_body" %>
		</div>

		<div class="actions row">
			<%= f.submit "Update Book",class: "btn btn-primary col-xs-12" %>
		</div>
		<% end %>


		<%= link_to "Show", @book, class: "book_#{@book.id}" %>
		|
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<!-- いいね機能 -->
					<td>
						<% if current_user.already_favorited?(book) %>
						<!-- いいね押していたとき -->
						<%= link_to book_favorites_path(book), method: :delete do %>
						<i class="glyphicon glyphicon-heart" ></i>
						<% end %>
						<% else %>
						<!-- いいねしていないとき -->
						<%= link_to book_favorites_path(book), method: :post do %>
						<i class="glyphicon glyphicon-heart" ></i>
						<% end %>
						<% end %>
						<%= book.favorites.count %>
					</td>
					<!-- コメント数 -->
					<td><p>コメント数：<%= book.book_comments.count %></p></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<thead>
				<tr>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
						<%= link_to user_path(@book.user_id) do %>
						<%= attachment_image_tag @book.user, :profile_image, size: "40x40",format:'jpeg', fallback: "no-image-mini.jpg" %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>

					<!-- いいね機能 -->
					<td>
						<% if current_user.already_favorited?(@book) %>
						<!-- いいね押していたとき -->
						<%= link_to book_favorites_path(@book), method: :delete do %>
						<i class="glyphicon glyphicon-heart"></i>
						<% end %>
						<% else %>
						　<!-- いいねしていないとき -->
						<%= link_to book_favorites_path(@book), method: :post do %>
						<i class="glyphicon glyphicon-heart"></i>
						<% end %>
						<% end %>
						<%= @book.favorites.count %>
					</td>
					<!-- コメント数 -->
					<td><p>コメント数：<%= @book.book_comments.count %></p></td>

					<!-- 編集・削除ボタン -->
					<% if current_user.id == @book.user_id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</tbody>
		</table>

		<!-- コメント本文 -->

		<% @book.book_comments.each do |book_comment| %>
		<div>
			<%= link_to user_path(book_comment.user_id) do %>
			<%= attachment_image_tag book_comment.user, :profile_image, size: "40x40",format:'jpeg', fallback: "no-image-mini.jpg" %><br>
			<%= book_comment.user.name %>
			<% end %>

			<%= book_comment.comment %>

			<% if book_comment.user == current_user %>
			<%= link_to "Destroy",book_book_comment_path(book_comment.book,book_comment), method: :delete, class: "btn-sm btn-danger" %>
			<% end %>
			<% end %>

		<!-- コメント入力欄 -->
		<%= form_for [@book,@book_comment] do |f| %>
		<div class="row">
			<div class="col-sm-12">
				<%= f.text_area :comment, rows:"5", class:"form-control",placeholder: "コメント入力欄" %>
			</div>
			<%= f.submit "Send", class:"btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>
		</div>
	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="body">
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

      <%= yield %>

    </div>
  </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% if current_user !== user %>
  <% if user.followed_by?(current_user) %>
      <%= link_to 'フォロー外す', user_relationships_path(user), class: 'btn btn-primary',method: :delete %>
  <% else %>
      <%=link_to 'フォローする', user_relationship(user), class: 'btn btn-success',method: :post %>
  <% end %>
<% end %>

app/views/users/_profile.html.erb
<table class="table">
	<tbody>
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>follows</th>
			<!-- フォロー数にフォロー一覧をリンク -->
			<th><%= link_to user.followings.count,follows_user_path(user) %></th>
		</tr>
		<tr>
			<th>followers</th>
			<!-- フォロワー数にフォロワー一覧をリンク -->
			<th><%= link_to user.followers.count,followers_user_path(user) %></th>
		</tr>
	</tbody>
</table>

<!-- マイページ以外にフォローボタン -->
<% if current_user != user %>
<% if user.followed_by?(current_user) %>
<%=link_to "フォロー外す", user_relationships_path(user),class: 'btn btn-primary', method: :delete %>
<% else %>
<%=link_to "フォローする", user_relationships_path(user),class: 'btn btn-success', method: :post %>
<% end %>
<% end %>

<!-- 編集ボタン -->
<% if user == current_user %>
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/followers.html.erb
<h1>Follower Users</h1>

<table class="table">
	<thead>
		<tr>
			<td>image</td>
			<td>name</td>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name %></td>
			<td>フォロー数：<%= user.followings.count %></td>
			<td>フォロワー数：<%= user.followers.count %></td>
			<td>
				<% if current_user != user %>
				<% if user.followed_by?(current_user) %>
				<%=link_to "フォロー外す", user_relationships_path(user),class: 'btn btn-primary', method: :delete %>
				<% else %>
				<%=link_to "フォローする", user_relationships_path(user),class: 'btn btn-success', method: :post %>
				<% end %>
				<% end %>
			</td>
			<td><%= link_to 'Show', user_path(user) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/follows.html.erb
<div class="row">
	<div class="col-xs-12">

		<h1>Follow Users</h1>

		<table class="table">
			<thead>
				<tr>
					<td>image</td>
					<td>name</td>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td>フォロー数：<%= user.followings.count %></td>
					<td>フォロワー数：<%= user.followers.count %></td>
					<td>
						<% if current_user != user %>
						<% if user.followed_by?(current_user) %>
						<%=link_to "フォロー外す", user_relationships_path(user),class: 'btn btn-primary', method: :delete %>
						<% else %>
						<%=link_to "フォローする", user_relationships_path(user),class: 'btn btn-success', method: :post %>
						<% end %>
						<% end %>
					</td>
					<td><%= link_to 'Show',user_path(user) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td>フォロー数：<%= user.followings.count %></td>
					<td>フォロワー数：<%= user.followers.count %></td>

					<!-- 自分以外にフォローボタン -->
					<td>
						<% if current_user != user %>
						<% if user.followed_by?(current_user) %>
						<%= link_to 'フォロー外す', user_relationships_path(user), class: 'btn btn-primary',method: :delete %>
						<% else %>
						<%=link_to 'フォローする', user_relationships_path(user), class: 'btn btn-success',method: :post %>
						<% end %>
						<% end %>
					</td>

					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">

		<!--books一覧 -->
		<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<!-- コメント数 -->
					<td><p>コメント数：<%= book.book_comments.count %></p></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
	<div class="col-xs-12">

		<h1>Follow Users</h1>

		<table class="table">
			<thead>
				<tr>
					<td>image</td>
					<td>name</td>
				</tr>
			</thead>
			<tbody>
				<% @user.followings.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td>フォロー数：<%= user.followings.count %></td>
					<td>フォロワー数：<%= user.followers.count %></td>
					<td></td>
					<td><%= link_to 'Show',user_path(user) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>